// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import "./libs/shim/expect.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "https://quickpizza.grafana.com"
  }
});

export default function() {
  postman[Request]({
    name: "1. Health",
    id: "cb53bf02-a5da-468d-9ba7-ac7be357da1b",
    method: "GET",
    address: "{{baseUrl}}/healthz",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "2. Ready",
    id: "b20910d2-f63f-4199-932d-55cbea275613",
    method: "GET",
    address: "{{baseUrl}}/ready",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "3. Status 418",
    id: "8b043450-25f6-459e-a933-3bfa4bd272c6",
    method: "GET",
    address: "{{baseUrl}}/api/status/418",
    post(response) {
      pm.test("status is 418", function() {
        pm.response.to.have.status(418);
      });
    }
  });

  postman[Request]({
    name: "4. GET Echo",
    id: "24912441-8d92-47e9-9cb9-885ceb0082d3",
    method: "GET",
    address: "{{baseUrl}}/api/get?source=postman-to-k6&kind=smoke",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "5. POST Echo JSON",
    id: "b98fa6bb-7d6a-4693-b910-197a3431b739",
    method: "POST",
    address: "{{baseUrl}}/api/post",
    data: '{\n  "hello": "quickpizza",\n  "count": 1\n}',
    headers: {
      "Content-Type": "application/json"
    },
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "6. PUT Echo Text",
    id: "504c953f-b9b1-4f68-81e8-ae67f395458d",
    method: "PUT",
    address: "{{baseUrl}}/api/put",
    data: "put-body",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "7. PATCH Echo Text",
    id: "eae7fc96-e34f-4d4b-98e1-c91338e13031",
    method: "PATCH",
    address: "{{baseUrl}}/api/patch",
    data: "patch-body",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "8. DELETE Echo",
    id: "f463f5e6-da41-4814-9392-c030f69b72f2",
    method: "DELETE",
    address: "{{baseUrl}}/api/delete",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "9. Quotes",
    id: "d2b5accc-5d32-41fe-bf13-070b00dc68a5",
    method: "GET",
    address: "{{baseUrl}}/api/quotes",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "10. Names",
    id: "0dbbf477-63e7-4f1a-a59a-834533463981",
    method: "GET",
    address: "{{baseUrl}}/api/names",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "11. Adjectives",
    id: "5c5fc31d-46ee-4823-91a7-a8d81ccba66c",
    method: "GET",
    address: "{{baseUrl}}/api/adjectives",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "12. Config",
    id: "18bd30de-4b20-4841-aa24-6b6b4d2eb6db",
    method: "GET",
    address: "{{baseUrl}}/api/config",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "13. Headers",
    id: "3eeb6db2-d2da-4753-a5d2-29c2ddc522ea",
    method: "GET",
    address: "{{baseUrl}}/api/headers",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "14. JSON Params",
    id: "bc13aed9-f265-4cf9-a5d2-eb11cbf533bb",
    method: "GET",
    address: "{{baseUrl}}/api/json?param1=value1&param2=value2",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "15. XML Params",
    id: "3f915a31-77b2-4f9c-b2d5-1965139f750f",
    method: "GET",
    address: "{{baseUrl}}/api/xml?param1=value1&param2=value2",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "16. Bytes 64",
    id: "2026a2db-8ced-42a0-b3d0-07bc9001405b",
    method: "GET",
    address: "{{baseUrl}}/api/bytes/64",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "17. Delay 1s",
    id: "a2418974-0547-4113-b210-aff95c5c07e9",
    method: "GET",
    address: "{{baseUrl}}/api/delay/1s",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "18. Metrics",
    id: "64dd66eb-b472-46d8-bf66-711b37a50c5e",
    method: "GET",
    address: "{{baseUrl}}/metrics",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "19. Capabilities Variables",
    id: "a12c3f8b-1d26-4d0a-9d3d-618e887a7589",
    method: "GET",
    address: "{{baseUrl}}/api/get?from={{capFromPre}}",
    pre() {
      pm.collectionVariables.set("capFromPre", "from-pre");
      pm.globals.set("capGlobal", "from-global");
      pm.variables.set("capLocal", "from-local");
    },
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
      pm.test("collection/global/local vars are available", function() {
        pm.expect(pm.collectionVariables.get("capFromPre")).to.eql("from-pre");
        pm.expect(pm.globals.get("capGlobal")).to.eql("from-global");
        pm.expect(pm.variables.get("capLocal")).to.eql("from-local");
      });
      pm.test("pm.info values are exposed", function() {
        pm.expect(pm.info.eventName).to.eql("test");
        pm.expect(pm.info.requestName).to.eql("19. Capabilities Variables");
      });
    }
  });

  postman[Request]({
    name: "20. Capabilities Json Assertions",
    id: "295abd2b-6e08-4a10-9653-2bcd617beb77",
    method: "GET",
    address: "{{baseUrl}}/api/json?param1=value1&param2=value2",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
      var body = pm.response.json();
      pm.test("pm.response.json works", function() {
        pm.expect(body.param1).to.eql("value1");
      });
      pm.test("jsonBody path/value works", function() {
        pm.response.to.have.jsonBody("param1", "value1");
      });
      pm.test("negative status assertion works", function() {
        pm.response.to.not.have.status(500);
      });
    }
  });

  postman[Request]({
    name: "21. Capabilities Header Assertions",
    id: "473a1470-1f4c-4b1c-b101-4c74eccf9dcb",
    method: "GET",
    address: "{{baseUrl}}/api/headers",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
      pm.test("header assertion works", function() {
        pm.response.to.have.header("content-type");
      });
      pm.test("headers API is available", function() {
        var headers = pm.response.headers.all();
        pm.expect(typeof headers).to.eql("object");
      });
    }
  });

  postman[Request]({
    name: "22. Capabilities Body Assertions",
    id: "b4915041-7a3f-4536-beb7-dcc6d2ae2946",
    method: "GET",
    address: "{{baseUrl}}/api/xml?paramA=one",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
      pm.test("body exists", function() {
        pm.response.to.have.body();
      });
      pm.test("body regex assertion works", function() {
        pm.response.to.have.body(/response/);
      });
      pm.test("negative body regex assertion works", function() {
        pm.response.to.not.have.body(/definitely_not_in_xml_body/);
      });
    }
  });

  postman[Request]({
    name: "23. Capabilities Set Cookie",
    id: "74b142f1-7961-4a5f-8c06-5e4278a646e5",
    method: "POST",
    address: "{{baseUrl}}/api/cookies?session_id=abc123",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "24. Capabilities Read Cookie",
    id: "f5924d0e-4250-4c91-9cf6-2ac260bc886f",
    method: "GET",
    address: "{{baseUrl}}/api/cookies",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
      var body = pm.response.json();
      pm.test("cookie roundtrip works", function() {
        pm.expect(body.cookies.session_id).to.eql("abc123");
      });
    }
  });

  postman[Request]({
    name: "25. Capabilities Request Metadata",
    id: "b302f6e9-6580-4052-b57f-93dffb5df2f7",
    method: "GET",
    address: "{{baseUrl}}/api/get?meta=true",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
      pm.test("request metadata is exposed", function() {
        pm.expect(pm.request.method).to.eql("GET");
        pm.expect(pm.info.requestName).to.eql(
          "25. Capabilities Request Metadata"
        );
      });
    }
  });

  postman[Request]({
    name: "26. Faker GET Params",
    id: "bc5277fc-5cd7-4723-8ea3-6923a9f9cc17",
    method: "GET",
    address:
      "{{baseUrl}}/api/json?firstName={{$randomFirstName}}&lastName={{$randomLastName}}&email={{$randomEmail}}&guid={{$guid}}&ts={{$timestamp}}",
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
      var body = pm.response.json();
      pm.test("faker request returned a json payload", function() {
        pm.expect(typeof body).to.eql("object");
      });
    }
  });

  postman[Request]({
    name: "27. Faker POST JSON",
    id: "ad45029c-1e2a-45d3-b0e0-4a3d9524de2b",
    method: "POST",
    address: "{{baseUrl}}/api/post",
    data:
      '{\n  "id": "{{$guid}}",\n  "profile": {\n    "username": "{{$randomUserName}}",\n    "city": "{{$randomCity}}",\n    "country": "{{$randomCountry}}"\n  },\n  "meta": {\n    "requestTime": "{{$isoTimestamp}}",\n    "randInt": "{{$randomInt}}"\n  }\n}',
    headers: {
      "Content-Type": "application/json"
    },
    post(response) {
      pm.test("status is 200", function() {
        pm.response.to.have.status(200);
      });
      pm.test("post body exists", function() {
        pm.response.to.have.body();
      });
    }
  });
}
