import collection from 'helper/collection';
import aggregate from 'generate/separate/aggregate';
test('success', () => {
  const node = collection('test/material/2.1/tree.json');
  const result = aggregate(node);
  expect(typeof result).toBe('object');
  expect(result.items.length).toBe(1);
  expect(result.locations.length).toBe(4);
  expect(result.locations[0].items.length).toBe(0);
  expect(result.locations[0].locations.length).toBe(2);
  expect(result.locations[0].locations[0].items.length).toBe(1);
  expect(result.locations[0].locations[0].locations.length).toBe(0);
  expect(result.locations[0].locations[1].items.length).toBe(2);
  expect(result.locations[0].locations[1].locations.length).toBe(0);
  expect(result.locations[1].items.length).toBe(1);
  expect(result.locations[1].locations.length).toBe(0);
  expect(result.locations[2].items.length).toBe(3);
  expect(result.locations[2].locations.length).toBe(0);
  expect(result.locations[3].items.length).toBe(3);
  expect(result.locations[3].locations.length).toBe(0);
});
