name: Build on push

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main

jobs:
  build-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install dependencies
        run: npm install

      - name: Format
        run: yarn format

      - name: Lint
        run: yarn lint

      - name: Test (Jest)
        run: npm run test-jest

      - name: Install Ava suite dependencies
        run: npm install --prefix tests/ava-suite

      - name: Test (Ava)
        run: npm --prefix tests/ava-suite run test-all

      - name: Bundle
        run: npm run bundle
