name: Build on push

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main

jobs:
  build-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Format
        run: yarn format

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Bundle
        run: yarn bundle
